# Generated by Django 5.0.4 on 2024-04-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_gender',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='user_phone_number',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='user_postcode',
            field=models.IntegerField(default=False),
        ),
    ]
